### Sci-kit Learn Pipelines
## Why pipeline?
Pipelines can keep our code neat and clean - from processing and cleaning our data & fine-tuning models!

Can help prevent mistakes (like data leakage and test set- for example during cross validation)

In [31]:
import pandas as pd

from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler,OneHotEncoder
from sklearn.model_selection import train_test_split

from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score,mean_squared_error

### Read In and Explore the Data

In [32]:
ames = pd.read_csv('data/ames.csv')
ames.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [33]:
ames.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   MSZoning       1460 non-null   object
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64
 5   Street         1460 non-null   object
 6   Alley          91 non-null     object
 7   LotShape       1460 non-null   object
 8   LandContour    1460 non-null   object
 9   Utilities      1460 non-null   object
 10  LotConfig      1460 non-null   object
 11  LandSlope      1460 non-null   object
 12  Neighborhood   1460 non-null   object
 13  Condition1     1460 non-null   object
 14  Condition2     1460 non-null   object
 15  BldgType       1460 non-null   object
 16  HouseStyle     1460 non-null   object
 17  OverallQual    1460 non-null   int64
 18  OverallCond    1460 non-null   int64
 19  YearBuilt      1460 non-null   int64
 20  YearRemodAdd   1460 non-null   int64
 21  RoofStyle      1460 non-null   object
 22  RoofMatl       1460 non-null   object
 23  Exterior1st    1460 non-null   object
 24  Exterior2nd    1460 non-null   object
 25  MasVnrType     1452 non-null   object
 26  MasVnrArea     1452 non-null   float64
 27  ExterQual      1460 non-null   object
 28  ExterCond      1460 non-null   object
 29  Foundation     1460 non-null   object
 30  BsmtQual       1423 non-null   object
 31  BsmtCond       1423 non-null   object
 32  BsmtExposure   1422 non-null   object
 33  BsmtFinType1   1423 non-null   object
 34  BsmtFinSF1     1460 non-null   int64
 35  BsmtFinType2   1422 non-null   object
 36  BsmtFinSF2     1460 non-null   int64
 37  BsmtUnfSF      1460 non-null   int64
 38  TotalBsmtSF    1460 non-null   int64
 39  Heating        1460 non-null   object
 40  HeatingQC      1460 non-null   object
 41  CentralAir     1460 non-null   object
 42  Electrical     1459 non-null   object
 43  1stFlrSF       1460 non-null   int64
 44  2ndFlrSF       1460 non-null   int64
 45  LowQualFinSF   1460 non-null   int64
 46  GrLivArea      1460 non-null   int64
 47  BsmtFullBath   1460 non-null   int64
 48  BsmtHalfBath   1460 non-null   int64
 49  FullBath       1460 non-null   int64
 50  HalfBath       1460 non-null   int64
 51  BedroomAbvGr   1460 non-null   int64
 52  KitchenAbvGr   1460 non-null   int64
 53  KitchenQual    1460 non-null   object
 54  TotRmsAbvGrd   1460 non-null   int64
 55  Functional     1460 non-null   object
 56  Fireplaces     1460 non-null   int64
 57  FireplaceQu    770 non-null    object
 58  GarageType     1379 non-null   object
 59  GarageYrBlt    1379 non-null   float64
 60  GarageFinish   1379 non-null   object
 61  GarageCars     1460 non-null   int64
 62  GarageArea     1460 non-null   int64
 63  GarageQual     1379 non-null   object
 64  GarageCond     1379 non-null   object
 65  PavedDrive     1460 non-null   object
 66  WoodDeckSF     1460 non-null   int64
 67  OpenPorchSF    1460 non-null   int64
 68  EnclosedPorch  1460 non-null   int64
 69  3SsnPorch      1460 non-null   int64
 70  ScreenPorch    1460 non-null   int64
 71  PoolArea       1460 non-null   int64
 72  PoolQC         7 non-null      object
 73  Fence          281 non-null    object
 74  MiscFeature    54 non-null     object
 75  MiscVal        1460 non-null   int64
 76  MoSold         1460 non-null   int64
 77  YrSold         1460 non-null   int64
 78  SaleType       1460 non-null   object
 79  SaleCondition  1460 non-null   object
 80  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(35), object(43)
memory usage: 924.0+ KB

In [34]:
#Explore contionous variables
ames.describe()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
count,1460.000000,1460.000000,1201.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1452.000000,1460.000000,...,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000
mean,730.500000,56.897260,70.049958,10516.828082,6.099315,5.575342,1971.267808,1984.865753,103.685262,443.639726,...,94.244521,46.660274,21.954110,3.409589,15.060959,2.758904,43.489041,6.321918,2007.815753,180921.195890
std,421.610009,42.300571,24.284752,9981.264932,1.382997,1.112799,30.202904,20.645407,181.066207,456.098091,...,125.338794,66.256028,61.119149,29.317331,55.757415,40.177307,496.123024,2.703626,1.328095,79442.502883
min,1.000000,20.000000,21.000000,1300.000000,1.000000,1.000000,1872.000000,1950.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2006.000000,34900.000000
25%,365.750000,20.000000,59.000000,7553.500000,5.000000,5.000000,1954.000000,1967.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,2007.000000,129975.000000
50%,730.500000,50.000000,69.000000,9478.500000,6.000000,5.000000,1973.000000,1994.000000,0.000000,383.500000,...,0.000000,25.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,2008.000000,163000.000000
75%,1095.250000,70.000000,80.000000,11601.500000,7.000000,6.000000,2000.000000,2004.000000,166.000000,712.250000,...,168.000000,68.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000,2009.000000,214000.000000
max,1460.000000,190.000000,313.000000,215245.000000,10.000000,9.000000,2010.000000,2010.000000,1600.000000,5644.000000,...,857.000000,547.000000,552.000000,508.000000,480.000000,738.000000,15500.000000,12.000000,2010.000000,755000.000000

In [35]:
#Explore categorical columns
ames.select_dtypes(include='object').describe()

,MSZoning,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,...,GarageType,GarageFinish,GarageQual,GarageCond,PavedDrive,PoolQC,Fence,MiscFeature,SaleType,SaleCondition
count,1460,1460,91,1460,1460,1460,1460,1460,1460,1460,...,1379,1379,1379,1379,1460,7,281,54,1460,1460
unique,5,2,2,4,4,2,5,3,25,9,...,6,3,5,5,3,3,4,4,9,6
top,RL,Pave,Grvl,Reg,Lvl,AllPub,Inside,Gtl,NAmes,Norm,...,Attchd,Unf,TA,TA,Y,Gd,MnPrv,Shed,WD,Normal
freq,1151,1454,50,925,1311,1459,1052,1382,225,1260,...,870,605,1311,1326,1340,3,157,49,1267,1198

### Outline initial approach
- Take the numeric columns only(excluding years)
- impute missing values with the median using a simpleimputer
- Scale the data using a standard scaler
- Model using LinearRegression

### Process the data

In [36]:
# Define ehich numeric columns we Dont want to use
# Not including target-related cols, plus the ID and year-related cols
not_used_num_cols = ['SalePrice','Id','YearBuilt','YearRemodAdd','MoSold', 'YrSold']
numeric_colums  = ames.select_dtypes(include=['Float64','int64']).columns 

# Define which columns to use
#Grabbing all numeric columns that aren't in the above list
used_columns = [col for col in numeric_colums if col not in not_used_num_cols]
used_columns

['MSSubClass',
 'LotFrontage',
 'LotArea',
 'OverallQual',
 'OverallCond',
 'MasVnrArea',
 'BsmtFinSF1',
 'BsmtFinSF2',
 'BsmtUnfSF',
 'TotalBsmtSF',
 '1stFlrSF',
 '2ndFlrSF',
 'LowQualFinSF',
 'GrLivArea',
 'BsmtFullBath',
 'BsmtHalfBath',
 'FullBath',
 'HalfBath',
 'BedroomAbvGr',
 'KitchenAbvGr',
 'TotRmsAbvGrd',
 'Fireplaces',
 'GarageYrBlt',
 'GarageCars',
 'GarageArea',
 'WoodDeckSF',
 'OpenPorchSF',
 'EnclosedPorch',
 '3SsnPorch',
 'ScreenPorch',
 'PoolArea',
 'MiscVal']

In [37]:
# Define our X and y
X = ames[used_columns]
y= ames['SalePrice']

#Train-test split
X_train,X_test,y_train,y_test =  train_test_split(X,y,test_size=0.25,random_state=13)

In [38]:
#Check our work
X_train.head()

,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,MasVnrArea,BsmtFinSF1,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,...,GarageYrBlt,GarageCars,GarageArea,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal
998,30,60.0,9786,3,4,0.0,0,0,1007,1007,...,1922.0,1,210,0,100,48,0,0,0,0
883,75,60.0,6204,4,5,0.0,0,0,795,795,...,1997.0,1,440,0,188,0,0,0,0,0
792,60,92.0,9920,7,5,0.0,862,0,255,1117,...,1997.0,2,455,180,130,0,0,0,0,0
617,45,59.0,7227,6,6,0.0,0,0,832,832,...,1962.0,2,528,0,0,0,0,0,0,0
1028,50,79.0,9492,5,5,0.0,368,41,359,768,...,1941.0,1,240,0,0,0,0,0,0,0

In [39]:
# Instantiate our imputer
imputer =  SimpleImputer(strategy='median')

#Fit our imputer on the training data
imputer.fit(X_train)

#create no-null versions of our train and test data
X_train_no_nulls = imputer.transform(X_train)
X_test_no_nulls = imputer.transform(X_test)

In [47]:
#instantiate our scaler
scaler = StandardScaler()
#Fit our scaler on the no-null training data
scaler.fit(X_train_no_nulls)

#create processed versions of our train and test data
X_train_processed= scaler.transform(X_train_no_nulls)
X_test_processed = scaler.transform(X_test_no_nulls)

In [48]:
X_train_processed.shape

(1095, 32)

### Model the Data

In [49]:
linreg = LinearRegression()
linreg.fit(X_train_processed,y_train)

#grab prdictions out on our train and test sets, to evaluate
train_preds = linreg.predict(X_train_processed)
test_preds = linreg.predict(X_test_processed)

In [52]:
# Print out R2-Score and Root Mean squared Error for our Train and test data
print(f'Train set R2-score: {r2_score(y_train,train_preds)}')
print(f'Train set RMSE: {mean_squared_error(y_train,train_preds,squared=False)}')
print('*'*20)
print(f'test set R2-score: {r2_score(y_test,test_preds)}')
print(f'test set RMSE: {mean_squared_error(y_test,test_preds,squared=False)}')

Train set R2-score: 0.8707199560814476
Train set RMSE: 28303.879274049435
********************
test set R2-score: 0.5098690507432813
test set RMSE: 56967.033764445056

In [54]:
linreg.score(X_train_processed,y_train)

0.8707199560814476

In [56]:
mean_squared_error(y_test,test_preds)

3245242935.919423

### Evaluate
We'd like to cross validate. to see if our modelling approach nees worls or if this is just a really bad split in the data.

But currently we're using median,mean and standard deviation of the training data in our processing steps (median for imputation, mean/std for our scaler).If we did cross-validation on already-processed data, there would be some set leakage in each of our folds, since  the test data in each fold would be affect our processing.Not good !

![](images/cross_validation.PNG)

### Enter:Pipelines
Pipelines are needed in this becasue each split inside the cross validation should be processed using only parameters from the training data for that split.
Pipelines make that effortless

In [58]:
#import pipeline
from sklearn.pipeline import Pipeline

### Recap our preprocessing steps
- Imputed null using simple imputer
- Scaled the data using standard scaller

In [67]:
#Now define those steps for our pipeline
processor = Pipeline(steps=[
    ('imputer',SimpleImputer(strategy='median')),
    ('scaler',StandardScaler())
])

In [68]:
#we go ahead and test this on our X_train from before, to make sure we get the same result
processor.fit_transform(X_train).shape

(1095, 32)

In [70]:
# Now add the model - using another pipeline
pipe = Pipeline(steps=[
    ('preprocessor',processor),
    ('linreg',LinearRegression())
])

pipe.fit(X_train,y_train)

#Grab predictions out on our train and test sets, to evaluate
train_preds = pipe.predict(X_train)
test_preds =pipe.predict(X_test)

In [75]:
#print out R2-Score and Root Mean squared Error for our train and test data
print(f'Train set r2-score:{r2_score(y_train,train_preds)}')
print(f'Train set RMSE: {mean_squared_error(y_train,train_preds,squared=False)}')
print('*'*20)
print(f'test set r2-score:{r2_score(y_test,test_preds)}')
print(f'test set RMSE: {mean_squared_error(y_test,test_preds,squared=False)}')

Train set r2-score:0.8707199560814476
Train set RMSE: 28303.879274049435
********************
test set r2-score:0.5098690507432813
test set RMSE: 56967.033764445056

### Cross validate

In [76]:
#Import our cross validation
#Note that cross_val_score and cross_val_predict are variants of this function
from sklearn.model_selection import cross_validate

In [78]:
#Time to cross val!
#Pass in our pipeline and training dta ,set cv=5 and return the train score
#because we're using cross-validatte instead of cross_val_score , can set scoring  metrics

results = cross_validate(pipe,X_train,y_train,cv=5,
                         return_train_score=True,
                         scoring=['r2','neg_root_mean_squared_error']
                         )
results

{'fit_time': array([0.01595807, 0.01296496, 0.00897622, 0.00897527, 0.00897837]),
 'score_time': array([0.00797892, 0.00299311, 0.00299072, 0.00299144, 0.00498557]),
 'test_r2': array([0.85127087, 0.87884364, 0.84017079, 0.84333297, 0.88909007]),
 'train_r2': array([0.87467718, 0.86804037, 0.87487314, 0.87649973, 0.86492754]),
 'test_neg_root_mean_squared_error': array([-31960.89470917, -24894.65236974, -28337.79957954, -34520.42150593,
        -26492.66030195]),
 'train_neg_root_mean_squared_error': array([-27481.89704448, -29210.96378414, -28480.63426708, -26860.96301849,
        -28853.2796904 ])}

In [86]:
#Let's look at the avreage, plus a meaure of variance for train and test
print(f'Average Train Set r2-Score: {results["train_r2"].mean()} +/- {results["train_r2"].std()}')
print(f'Average Train Set RMSE: {results["train_neg_root_mean_squared_error"].mean()*-1} +/- {results["train_neg_root_mean_squared_error"].std()}')
print('*'*20)
#Let's look at the avreage, plus a meaure of variance for train and test
print(f'Average test Set r2-Score: {results["test_r2"].mean()} +/- {results["test_r2"].std()}')
print(f'Average test Set RMSE: {results["test_neg_root_mean_squared_error"].mean()*-1} +/- {results["test_neg_root_mean_squared_error"].std()}')

Average Train Set r2-Score: 0.8718035924327042 +/- 0.004498341306879644
Average Train Set RMSE: 28177.54756091705 +/- 875.6425127939331
********************
Average test Set r2-Score: 0.8605416690645816 +/- 0.019733387725523487
Average test Set RMSE: 29241.285693265625 +/- 3536.382277882743

In [ ]:
#Let's look at the avreage, plus a meaure of variance for train and test
print(f'Average Train Set r2-Score:{results['train_r2'].mean()} +/- {results['train_r2'].std()}')